### ISSUE TITLE
Navigation/index 

### ISSUE THREAD

**Issue by ltakens** [svx/plone.virtualbox.appliance#1]
![nav](https://cloud.githubusercontent.com/assets/12794611/8695943/cdbec8b0-2ae8-11e5-990e-03022fc852ec.png)

No nav menu on the left side in the setup section.

![order](https://cloud.githubusercontent.com/assets/12794611/8696012/447edcd8-2ae9-11e5-9ca8-0193b2189d95.png)

Also, order of content differs for left nav menu/in-text menu

**Comment by svx** [comment]
fixed
